version: '3.1'

services:
  mongo:
    image: mongo:6.0
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_DATABASE: nest-api-starter
      MONGO_INITDB_ROOT_USERNAME: docker
      MONGO_INITDB_ROOT_PASSWORD: mongopw
    volumes:
      - mongo_data_db:/data/db

volumes:
  mongo_data_db:
